### PR TITLE
Update noxutil.py

### PR DESCRIPTION
**Pull request by mforbes**
Add `python` parameter to `get_version()` allowing one to limit versions based on the python version.

This allows one to parse multiple requirements like 

```toml
Sphinx = [
  {version = ">=3.4.2,<6.0.0", python = "<3.9"},
  {version = ">=3.4.2,!=3.5.*,!=4.0.*,!=4.1.*,<6.0.0", python = ">=3.10"}
]
```

### CODE REVIEW

**Comment by brechtm** [comment]
Thanks @mforbes!

It's not obvious to me how this can be used. Do you happen to have an example noxfile.py where this is used? I suspect I may be able to use it here: https://github.com/brechtm/rinohtype/blob/5de15f0d6e9247491a7e0b268a3b4a82df5fb975/noxfile.py#L70

**Comment by brechtm** [comment]
My first test: `get_versions('sphinx', 'minor', python='x.y')` always returns the same list of Sphinx versions, regardless of _x_ and _y_.

**Comment by mforbes** [comment]
Sorry, yes, an example `noxfile.py` would probably have been useful.  I am doing something like this, since there does not seem to be a better way of determining the python version at the time that the decorator is called.  It is a bit ugly:

```python
sys.path.append(".")
from noxutils import get_versions

python_versions = ["3.6", "3.7", "3.8", "3.9", "3.10"]
@session(reuse_venv=True)
@nox.parametrize("python,sphinx",
                 sum([[(python, sphinx)
                       for sphinx in get_versions("sphinx", "minor", python=python)]
                      for python in python_versions],
                     []),
                 )
def test(session, sphinx):
    # nox_poetry uses the info in poetry.lock but you need to specify the test
    # dependencies here:
    session.install("sphinx-testing", "pytest-cov", ".")
    # Override sphinx, but using get_versions() makes sure this is consistent
    session.run("pip", "install", f"sphinx=={sphinx}")
    session.run("pytest")
```

**Comment by brechtm** [comment]
I was able to get closer to get it working once I realized that I needed to set python-version dependent Sphinx requirements in my _pyproject.toml_ (as you suggested in your original comment). I needed to upgrade Poetry because I ran into an issue with it generating an invalid version constraint (I forgot the details, unfortunately), but now I'm running into https://github.com/python-poetry/poetry-plugin-export/issues/118, so I'll first need to fix that before I can start using this.

**Comment by brechtm** [comment]
Merged. Many thanks for taking the time to make this PR!

**Pull request merged**
